/*
	- PERSONA
		> COLEGIADO
			>> PERITO
		> PRECOLEGIADO
		> ADMINISTRATIVO (OPCIONAL)
		> CANDIDATO (COLEGIO)
		> PROFESOR (RESPONSABLE DE FORMACIÓN?) (OPCIONAL)
	
	- CURSO
*/

CREATE TABLE PERSONA
{
	P_ID		NUMBER,
	DNI 		VARCHAR2,
	NOMBRE 		VARCHAR2,
	APELLIDO 	VARCHAR2,
	POBLACION 	VARCHAR2,
	TELEFONO	NUMBER,
	
	CONSTRAINT PK_PERSONA PRIMARY KEY (P_ID),
	CONSTRAINT CK_PERSONA UNIQUE (DNI)
}

CREATE TABLE INTERESADO
{
	I_ID 		NUMBER,
	P_ID		NUMBER, 
	-- Datos académicos
	TITULACION	VARCHAR2,
	CENTRO		VARCHAR2,
	AÑO			YEAR,
	-- Datos bancarios
	ISBN		NUMBER,
	
	...
}

CREATE TABLE COLEGIADO
{
	I_ID		NUMBER,
	N_COLEGIADO	NUMBER,
	
	CONSTRAINT PK_COLEGIADO PRIMARY KEY (I_ID, N_COLEGIADO),
	CONSTRAINT FK_I_ID FOREIGN KEY (I_ID) REFERENCES INTERESADO (I_ID)
	
}

CREATE TABLE CURSO
{
	C_ID		NUMBER, 
	TITULO		VARCHAR2,
	PRECIO		MONEY,
	FECHA		DATE,
	ESTADO		VARCHAR2,
	PLAZAS		NUMBER,
	
	INS_INICIO	DATE,
	INS_FINAL	DATE,
	
	CONSTRAINT PK_CURSO PRIMARY KEY (C_ID),
	CONSTRAINT CHK_ESTADO_CURSO CHECK (ESTADO IN ('PLANIFICADO', 'ABIERTO', 'CERRADO', 'CANCELADO')),
	CONSTRAINT CHK_FECHAS CHECK ()
}

CREATE TABLE INSCRITO_EN
{
	P_ID		NUMBER, 
	C_ID		NUMBER,
	FECHA_INS	DATE,
	ESTADO_INS	VARCHAR2,
	
	CONSTRAINT PK_INSCRITO_EN PRIMARY KEY (P_ID, C_ID),
	CONSTRAINT FK_P_ID FOREIGN KEY (P_ID) REFERENCES PERSONA (P_ID),
	CONSTRAINT FK_C_ID FOREIGN KEY (C_ID) REFERENCES CURSO (C_ID),
	-- Comprobando que haya plazas disponibles (plazas - inscritos > 0)
	CONSTRAINT CHK_PLAZAS CHECK (
		(SELECT PLAZAS FROM CURSO WHERE CURSO.C_ID = C.ID) 
		 -
		(SELECT COUNT(P_ID) FROM INSCRITO_EN I WHERE C_ID=I.C_ID)
		 > 0
	),
	CONSTRAINT CHK_ESTADO_INS CHECK (ESTADO_INS IN ('PRE-INSCRITO', 'INSCRITO', 'CANCELADO'))
}
	