drop table if exists CURSO;
drop table if exists INSCRITO_EN;
drop table if exists COLEGIADO;
drop table if exists RECIBO;

--TABLA PARA LOS CURSOS--

CREATE TABLE CURSO(C_ID	INT PRIMARY KEY NOT NULL, TITULO VARCHAR(32) NOT NULL ,PRECIO FLOAT NOT NULL,FECHA DATE NOT NULL,ESTADO	VARCHAR (32) CHECK (ESTADO IN ('PLANIFICADO','ABIERTO','CERRADO')) NOT NULL,PLAZAS int,INS_INICIO DATE,INS_FINAL DATE , CHECK (INS_INICIO <= INS_FINAL));


--TABLA COLEGIADO--

CREATE TABLE COLEGIADO (N_COLEGIADO VARCHAR(32) PRIMARY KEY NOT NULL, PRECOLEG BOOLEAN NOT NULL ,ESTADO VARCHAR(15) CHECK (ESTADO IN ('PENDIENTE','ACEPTADO')) NOT NULL,DNI VARCHAR(9) CHECK (DNI LIKE '\d\d\d\d\d\d\d\d\w') UNIQUE NOT NULL,NOMBRE VARCHAR(32) NOT NULL,APELLIDOS VARCHAR(32) NOT NULL,POBLACION VARCHAR(32) NOT NULL,TELEFONO INTEGER(9) CHECK (TELEFONO LIKE '\d\d\d\d\d\d\d\d\d') NOT NULL,TITULACION VARCHAR(32) NOT NULL,CENTRO VARCHAR(32) NOT NULL,AÑO DATE NOT NULL, ISBN VARCHAR(32) NOT NULL);


--TABLA INSCRITO_EN --

CREATE TABLE INSCRITO_EN(N_COLEGIADO VARCHAR(32) NOT NULL,ESTADO VARCHAR(32) CHECK (ESTADO IN ('PRE-INSCRITO','INSCRITO','CANCELADO')) NOT NULL, C_ID VARCHAR(32) NOT NULL ,FOREIGN KEY (N_COLEGIADO) REFERENCES COLEGIADO (N_COLEGIADO),FOREIGN KEY (C_ID) REFERENCES CURSO (C_ID), CONSTRAINT PK_INSCRITO_EN PRIMARY KEY (N_COLEGIADO, C_ID));

--TABLA RECIBO--

CREATE TABLE RECIBO( N_RECIBO VARCHAR(32) PRIMARY KEY NOT NULL, FECHA_EMISION DATE NOT NULL, DNI VARCHAR(9) NOT NULL, ISBN VARCHAR(32) NOT NULL,CANTIDAD FLOAT NOT NULL ,FOREIGN KEY (DNI) REFERENCES COLEGIDO (DNI), FOREIGN KEY (ISBN) REFERENCES COLEGIDO (ISBN) );	
